# Generated by Django 4.0.6 on 2023-07-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konnektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_id', models.IntegerField(blank=True, null=True)),
                ('k_name', models.CharField(blank=True, max_length=200, null=True)),
                ('k_is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('k_online_since', models.CharField(blank=True, max_length=200, null=True)),
                ('k_firmware_version', models.CharField(blank=True, max_length=200, null=True)),
                ('k_update_available', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
